#!/bin/bash

# Ensure the correct command is found:
export PATH="/home/D57673/BUILD/MASTER_PERF/code_saturne.install/bin":$PATH

# Insert default command
cs_cmd=""
if test $# = 1; then
  if test -f $1; then
    cs_cmd=gui
  fi
elif test $# = 0; then
  cs_cmd=gui
fi

# Run command
\code_saturne $cs_cmd "$@"
